version: "3.9"

services:
  app:
    image: ask09/node-mongodb-app:latest
    container_name: node-app
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network

  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
